Cobee/urls.py
from django.conf.urls import url
from django.contrib import admin

from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
]

blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
	# Example: /
	url(r'^$', PostLV.as_view(), name='index'),

	# Example: /post/ (same as /)
	url(r'^post/$', PostLV.as_view(), name='post_list'),

	# Example: /post/django-example/
	url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

	# Example: /archive/
	url(r'^archive/$', PostAV.as_view(), name='post_archive'),

	# Example: /2012/
	url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

	# Example: /2012/nov/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

	# Example: /2012/nov/1/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

	# Example: /today/
	url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

	# Example: /tag/
	url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

	# Example: /tag/tagname/
	url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

	# Example: /search/
	url(r'^search/$', SearchFormView.as_view(), name='search'),

	#Example: /add/
    url(r'^add/$', PostCreateView.as_view(), name="add",),

    #Example: /change/
    url(r'^change/$', PostChangeLV.as_view(), name="change",),

    #Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update",),

    #Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete",),
]

blog_project2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from blog_project2.views import HomeView
from blog_project2.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse
from tagging.fields import TagField
from django.contrib.auth.models import User
from django.utils.text import slugify

class Post(models.Model):
	title = models.CharField('TITLE', max_length=50)
	slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
	description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
	content = models.TextField('CONTENT')
	create_date = models.DateTimeField('Create Date', auto_now_add = True)
	modify_date = models.DateTimeField('Modify Date', auto_now = True)
	tag = TagField()
	owner = models.ForeignKey(User, null=True)

	class Meta:
		verbose_name = 'post'
		verbose_name_plural = 'posts'
		db_table = 'my_post'
		ordering = ('-modify_date',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=(self.slug,))

	def get_previous_post(self):
		return self.get_previous_by_modify_date()

	def get_next_post(self):
		return self.get_next_by_modify_date()

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.title, allow_unicode=True)
		super(Post, self).save(*args, **kwargs)

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
	search_word = forms.CharField(label='Search Word')

blog/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from django.views.generic.edit import FormView
from blog.forms import PostSearchForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from blog_project2.views import LoginRequiredMixin

from django.db.models import Q
from django.shortcuts import render

class TagTV(TemplateView):
	template_name = 'tagging/tagging_cloud.html'

class PostLV(ListView):
	model = Post
	template_name = 'blog/post_all.html'
	context_object_name = 'posts'
	paginate_by = 2

class PostTOL(TaggedObjectList):
	model = Post
	template_name = 'tagging/tagging_post_list.html'

class PostDV(DetailView):
	model = Post

class PostAV(ArchiveIndexView):
	model = Post
	date_field = 'modify_date'

class PostYAV(YearArchiveView):
	model = Post
	date_field = 'modify_date'
	make_object_list = True

class PostMAV(MonthArchiveView):
	model = Post
	date_field = 'modify_date'

class PostDAV(DayArchiveView):
	model = Post
	date_field = 'modify_date'

class PostTAV(TodayArchiveView):
	model = Post
	date_field = 'modify_date'

#---- FormView
class SearchFormView(FormView):
	form_class = PostSearchForm
	template_name = 'blog/post_search.html'

	def form_valid(self, form):
		schWord = '%s' % self.request.POST['search_word']
		post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()

		context = {}
		context['form'] = form
		context['search_term'] = schWord
		context['object_list'] = post_list

		return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'slug', 'description', 'content', 'tag']
	initial = {'slug': 'auto-filling-do-not-input'}
	#fields = ['title', 'description', 'content', 'tag']
	success_url = reverse_lazy('blog:index')

	def form_valid(self, form):
		form.instance.owner = self.request.user
		return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
	template_name = 'blog/post_change_list.html'

	def get_queryset(self):
		return Post.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView):
	model = Post
	fields = ['title', 'slug', 'description', 'content', 'tag']
	success_url = reverse_lazy('blog:index')

class PostDeleteView(LoginRequiredMixin, DeleteView):
	model = Post
	success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %} post_all.html {% endblock %}

{% block content %}
<div id="content">

<h1>Blog List</h1>

{% for post in posts %}
	<h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
	{{ post.modify_date|date:"N d, Y" }}
	<p>{{ post.description }}</p>
{% endfor %}

<br/>

<div>
	<span>
		{% if page_obj.has_previous %}
			<a href="?page_obj.next_page_number }}">PreviousPage</a>
		{% endif %}

		Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">NextPage</a>
		{% endif %}
	</span>
</div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %} post_archive.html {% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
	{% for date in date_list %}
	<li style="display: inline;">
		<a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}
</a></li>
	{% endfor %}
</ul>
<br/>

<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %} post_archive_day.html {% endblock %}

{% block content %}
<div id="content">

<h1>post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %} post_archive_month.html {% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %} post_archive_year.html {% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
	{% for date in date_list %}
	<li style="display: inline;">
		<a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}"> {{ date|date:"F" }}</a></li>
	{% endfor %}
</ul>
<br/>

<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>
{% edblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %} post_detail.html {% endblock %}

{% block content %}
<div id="content">

<h2>{{ object.title }} </h2>

<p class="other_posts">
	{% if object.get_previous_by_modify_date %}
	<a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post"> &laquo;--{{ object.get_previous_post }}</a>
	{% endif %}

	{% if object.get_next_by_modify_date %}
	| <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post"> {{ object.get_next_post }}--&raquo;</a>
	{% endif %}
</p>

<p class = "date"> {{ object.modify_date|date:"j F Y" }}</p>
<br/>

<div class="body">
	{{ object.content|linebreaks }}
</div>

<div>
<b>TAGS: </b>
{% load tagging_tags %}
{% tags_for_object object as tags %}
{% for tag in tags %}
<a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
{% endfor %}
<a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
</div>
<br/>
<div>
{% load disqus_tags %}
{% disqus_show_comments %}
</div>
{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}
{% block title%}post_search.html{% endblock %}

{% block content %}
<div id="content">

<h1>Blog Search</h1>

<form action="." method="post"> {% csrf_token %}
	{{ form.as_table }}
	<input type ="submit" value="검색" />
</form>

<br/><br/>

{% if object_list %}
{% for post in object_list %}
	<h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
	{{ post.modify_date|date:"N d, Y" }}
	<p>{{ post.description }}</p>
{% endfor %}

{% elif search_term %}
<b>검색 결과 = ({{ search_term }}) (이)라는 내용은 유감스럽게도 없네^^ !</b>
{% endif %}

</div>
{% endblock %}