Cobee/urls.py
from django.conf.urls import url
from django.contrib import admin

from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
]

blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
	# Example: /
	url(r'^$', PostLV.as_view(), name='index'),

	# Example: /post/ (same as /)
	url(r'^post/$', PostLV.as_view(), name='post_list'),

	# Example: /post/django-example/
	url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

	# Example: /archive/
	url(r'^archive/$', PostAV.as_view(), name='post_archive'),

	# Example: /2012/
	url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

	# Example: /2012/nov/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

	# Example: /2012/nov/1/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

	# Example: /today/
	url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

	# Example: /tag/
	url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

	# Example: /tag/tagname/
	url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

	# Example: /search/
	url(r'^search/$', SearchFormView.as_view(), name='search'),

	#Example: /add/
    url(r'^add/$', PostCreateView.as_view(), name="add",),

    #Example: /change/
    url(r'^change/$', PostChangeLV.as_view(), name="change",),

    #Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update",),

    #Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete",),
]

blog_project2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from blog_project2.views import HomeView
from blog_project2.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<title>★코비 월드★</title>

<head>
	<title>{% block title %}Django Web Programming{% endblock %}</title>

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
	<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
</head>

<body>
	<div id = "header">
		<h1 class="maintitle">코비의 신나는 호러세상^_^</h1>
		{% if user.is_active %}
		<h4 class="welcome">Welcome, 
				<strong>{% firstof user.get_short_name user.get_username %}</strong> /
				<a href="{% url 'password_change' %}">비밀번호 변경</a> /
				<a href="{% url 'logout' %}">로그아웃</a>
		</h4>
		{% else %}
		<h4 class="welcome">Guest로 입장하셨습니다. /
				<a href="{% url 'login' %}">로그인 </a> /
				<a href="{% url 'register' %}">회원가입 </a>
		</h4>
		{% endif %}
	</div>

	<div id="menu">
		<li><a href="{% url 'home' %}">Home</a></li>
		<li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
		<li><a href="{% url 'blog:index' %}">Blog</a></li>
		<li><a href="{% url 'photo:index' %}">Photo</a></li>

		<li><a href="#">Add&bigtriangledown;</a>
			<ul>
				<li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
				<li><a href="{% url 'blog:add' %}">Post</a></li>
				<li><a href="#">Photo</a></li>
			</ul>
		</li>
		<li><a href="#">Change&bigtriangledown;</a>
			<ul>
				<li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
				<li><a href="{% url 'blog:change' %}">Post</a></li>
				<li><a href="#">Photo</a></li>
			</ul>
		</li>

		<li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
		<li><a href="{% url 'blog:search' %}">Search</a></li>
		<li><a href="{% url 'admin:index' %}">Admin</a></li>
	</div>

	{% block content %}{% endblock %}
	{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}


{% block content %}

<div id = "content_home">

	<div id="homeing">
		<a href="/"><img src="{% static 'img/d123.jpg' %}" style="height:500px; display: block; margin-left: auto; margin-right: auto;"/></a>
		<h2 style="margin: 0; text-align: center;">코비의 재미난 코딩사이트에 오신것을 진심으로 환영할줄 알았냐?</h4>
	</div>

	<hr style="margin: 5px 0;">

	<h2 align="center">Select Application</h2>

	<table id="applist" align="center">
		<tr>
		<td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
		<td>ㅈㄴ 쓸데없는 북마크</td>
		<td class="Edit"><i><a href="#">Add</a></i></td>
		<td class="Edit"><i><a href="#">Change</a></i></td>
		</tr>

		<tr>
		<td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
		<td>이 세상의 모든 사이트를 저장하자</td>
		<td class="Edit"><i><a href="#">Add</a></i></td>
		<td class="Edit"><i><a href="#">Change</a></i></td>
		</tr>

		<tr>
		<td><b><i><a href="#">Photo</a></i></b></td>
		<td>므흣...>_<</td>
		<td class="Edit"><i><a href="#">Add</a></i></td>
		<td class="Edit"><i><a href="#">Change</a></i></td>
		</tr>
	</table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
	&copy; Cobee 2017
</div>
{% endblock footer %}